# Membuat pod
# kubectl create -f namefile.yaml

# Menghapus pod
# kubectl delete pod namepod1 namepod2

# Menghapus pod berdasarkan label
# kubectl delete pod -l environment=development

# Mengahpus pod berdasarkan namespace
# kubectl delete pod -all --namespace (namespace)

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
    version: 1.4.5
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
