# Jika ingin coba2 cronjob expresiion bisa mengunjungi web ini
# -> https://crontab.guru

apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodejs-cronjob
  labels:
    name: nodejs-cronjob
spec:
  schedule: "* * * * *" # ini berarti job akan mengeksekusi saat 1 menit pertama
  jobTemplate:
    spec:
      template:
        metadata:
          name: nodejs-cronjob
          labels:
            name: nodejs-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs-cronjob
              image: mhmdiamd/nodejs-job
